version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: drewbase
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
  
  web:
    build: .
    container_name: code
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
