# Generated by Django 3.2.12 on 2022-04-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField()),
                ('directory', models.CharField(default='', max_length=100)),
                ('file_size', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('directory', models.CharField(default='/home/drew/Documents/MusicBot', max_length=100)),
                ('version', models.CharField(default='', max_length=100)),
                ('server', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
