# Generated by Django 3.2.12 on 2022-04-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepost',
            name='game',
            field=models.CharField(choices=[('VALHEIM', 'Valheim'), ('MINECRAFT', 'Minecraft'), ('MUSICBOT', 'MusicBot'), ('KEEPASSXC', 'KeePassXC')], default='VALHEIM', max_length=100),
        ),
    ]
